---
title: "PS1 No.1A Rebecca"
author: "Rebecca"
date: ""
output:
  html_document:
    df_print: paged
  df_print: kable
  pdf_document:
    keep_tex: yes
toc: no
---

```{r setup, include=FALSE}
library(tidyverse)
library(FE)
library(psych)
library(knitr)

daily <- DJ_d$r_Dow_Jones
weekly <- DJ_w$r_close
```

## Statistical Properties of Asset Returns
### Distributional properties of Dow Jones index returns
> 1)

```{r plot1A1.1, echo=F}
plot1A1.1 <- ggplot(data=DJ_d) + geom_line(aes(x=1:nrow(DJ_d), y=r_Dow_Jones)) +
  labs(x='Time horizon', y='Log return', title='Dow Jones daily log returns')
plot1A1.1 + theme_classic()
```

For both: mention variance spikes (at same time? that's what i need proper labels for), hard to say anything about the time series' property, looks stationary but can't say.
```{r distrib prop, echo=F}
distr_daily <- data.frame(describe(DJ_d$r_Dow_Jones), row.names = "Daily")
distr_weekly <- data.frame(describe(DJ_w$r_close), row.names = "Weekly")

dat.df <- t(rbind.data.frame(distr_daily, distr_weekly))
kable(dat.df)
# mad = median absolute deviation from the median)
```

> 2)

```{r qq t weekly, echo=F}
#weekly
std_weekly_t = std_weekly*sqrt(df/(df-2))
qqplot(rt(length(std_weekly_t), df = df), std_weekly_t,  main = "T-distribution Q-Q plot for weekly log returns", xlab = "Theoretical Quantiles", ylab = "Sample Quantiles")
qqline(std_weekly_t, col = "red")
```

> 3)

```{r test normal, echo=F}
b = 30
bin = 1:b/b

#daily
r_nor = pnorm(std_daily)
hist(r_nor, breaks = 50)

vn = NULL
for(val in bin) vn = c(vn,sum(r_nor <= val)) 
vn = c(vn[1],diff(vn))
chi_test = sum((vn-length(std_daily)/b)**2/(length(std_daily)/b))
cat("test =",chi_test," df =",b-3," p-value =",1-pchisq(chi_test,df=b-3))

#weekly
r_nor_w = pnorm(std_weekly)
hist(r_nor_w, breaks=50)

vn_w = NULL
for(val in bin) vn_w = c(vn_w,sum(r_nor_w <= val)) #try to compute the frequency for the bins
vn_w = c(vn_w[1],diff(vn_w)) # put 1st value because differencing (why?) loses the first observation; vector of probabilities?
chi_test_w = sum((vn_w-length(std_daily)/b)**2/(length(std_weekly)/b))
cat("test =",chi_test_w," df =",b-3," p-value =",1-pchisq(chi_test_w,df=b-3))
```

Refer to Rosenblatt and show one histogram

```{r test t, echo=F}
df = 4

#daily
r_t = pt(std_daily_t,df=df)
hist(r_t, breaks=50)
vt = NULL; for(val in bin) vt = c(vt,sum(vt <= val))
vt = c(vt[1],diff(vt))
test = sum((vt-length(std_daily_t)/b)**2/(length(std_daily_t)/b)) # he used the std. normal data, not for t-dist.
cat("test =",test," df =",b-3," p-value =",1-pchisq(test,df=b-3)) # p-value = 0, reject t distr.
#diff. output than his (df, test etc)

#weekly
r_t_w = pt(std_weekly_t,df=df)
hist(r_t_w, breaks=50)
vt_w = NULL; for(val in bin) vt_w = c(vt_w,sum(vt_w <= val))
vt_w = c(vt[1],diff(vt_w))
test = sum((vt_w-length(std_daily_t)/b)**2/(length(std_daily_t)/b))
cat("test =",test," df =",b-3," p-value =",1-pchisq(test,df=b-3))
```

```{r test mix, echo=F}
#arbitrary choice
alpha = 0.4
sigma = 2.7 # this is the var of the second normal distr. and the first one is std_daily?

#daily
mix_daily = std_daily*sqrt((1-alpha) + alpha*sigma**2) #as data is std. and needs to be multiplied with var of mixed distr.
r_mix = (1-alpha)*pnorm(mix_daily) + alpha*pnorm(mix_daily,sd=sigma) #corresp. CDF of the mixture normal distr.
hist(r_mix)
vn_mix = NULL; for(val in bin) vn_mix = c(vn_mix,sum(r_mix <= val))
vn_mix = c(vn_mix[1],diff(vn_mix))
test = sum((vn_mix-length(std_daily)/b)**2/(length(std_daily)/b))
cat("test =",test," df =",b-3," p-value =",1-pchisq(test,df=b-3))

#optimization daily
func <- function(vx){
  alpha = vx[1]
  sigma = vx[2]
  mix_daily_opt = std_daily*sqrt((1-alpha) + alpha*sigma**2)

  r_mix_opt = (1-alpha)*pnorm(mix_daily_opt) + alpha*pnorm(mix_daily_opt,sd=sigma)
  vn_mix_opt = NULL; for(val in bin) vn_mix_opt = c(vn_mix_opt,sum(r_mix_opt <= val))
  vn_mix_opt = c(vn_mix_opt[1],diff(vn_mix_opt))
  return(sum((vn_mix_opt-length(std_daily)/b)**2/(length(std_daily)/b)))
}
#vx just a pair of parameters

##### what's happening here??
func(c(0.15,4))

res = optim(par=c(0.1,4),fn=func,method="BFGS") # this is not cherry-picking, this is optimizing (similar to OLS)

res
1-pchisq(res$value,df=b-3)
#alpha = 0.196 irgendwas, sigma = 2.66 irgendwas --> p-value becomes bigger than 1%, best we can get
####

#optimization weekly
func <- function(vx){
  alpha = vx[1]
  sigma = vx[2]
  mix_weekly_opt = std_weekly*sqrt((1-alpha) + alpha*sigma**2)

  r_mix_opt_w = (1-alpha)*pnorm(mix_weekly_opt) + alpha*pnorm(mix_weekly_opt,sd=sigma)
  vn_mix_opt_w = NULL; for(val in bin) vn_mix_opt_w = c(vn_mix_opt_w,sum(r_mix_opt_w <= val))
  vn_mix_opt_w = c(vn_mix_opt_w[1],diff(vn_mix_opt_w))
  return(sum((vn_mix_opt_w-length(std_weekly)/b)**2/(length(std_weekly)/b)))
}

#### adjust
func(c(0.15,4))

optim(par=c(0.1,4),fn=func,method="BFGS")
####
```
